### ISSUE TITLE
No Ping/IP showing after updating to v2.0

### ISSUE THREAD

**Issue by Xorag** [karashiiro/PingPlugin#38]
Hi, I just updated to 2.0 on windows 10, no VPN (steam version) and I always see 0ms ping now and no IP address in connected to:

I'm also on the crystal datacenter

I found this stack trace in my dalamud log:

2022-01-28 17:13:08.421 -05:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PingPlugin.PingTrackers.PingTracker.AddressUpdateLoop(CancellationToken token) in K:\arashiiro\PingTrackers\PingTracker.cs:line 68
   --- End of inner exception stack trace ---
2022-01-28 17:13:08.429 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wMS0yOFQxNzoxMzowOC40MjY5OC0wNTowMCIsIkluZm8iOiJTeXN0ZW0uQWdncmVnYXRlRXhjZXB0aW9uOiBBIFRhc2sncyBleGNlcHRpb24ocykgd2VyZSBub3Qgb2JzZXJ2ZWQgZWl0aGVyIGJ5IFdhaXRpbmcgb24gdGhlIFRhc2sgb3IgYWNjZXNzaW5nIGl0cyBFeGNlcHRpb24gcHJvcGVydHkuIEFzIGEgcmVzdWx0LCB0aGUgdW5vYnNlcnZlZCBleGNlcHRpb24gd2FzIHJldGhyb3duIGJ5IHRoZSBmaW5hbGl6ZXIgdGhyZWFkLiAoT2JqZWN0IHJlZmVyZW5jZSBub3Qgc2V0IHRvIGFuIGluc3RhbmNlIG9mIGFuIG9iamVjdC4pXHJcbiAtLS0+IFN5c3RlbS5OdWxsUmVmZXJlbmNlRXhjZXB0aW9uOiBPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LlxyXG4gICBhdCBQaW5nUGx1Z2luLlBpbmdUcmFja2Vycy5QaW5nVHJhY2tlci5BZGRyZXNzVXBkYXRlTG9vcChDYW5jZWxsYXRpb25Ub2tlbiB0b2tlbikgaW4gSzpcXGFyYXNoaWlyb1xcUGluZ1RyYWNrZXJzXFxQaW5nVHJhY2tlci5jczpsaW5lIDY4XHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLSIsIkNvbnRleHQiOiJVbm9ic2VydmVkIGV4Y2VwdGlvbiBpbiBUYXNrLiJ9
2022-01-28 17:13:08.429 -05:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Value cannot be null. (Parameter 'address'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'address')
   at System.Net.NetworkInformation.Ping.CheckArgs(IPAddress address, Int32 timeout, Byte[] buffer, PingOptions options)
   at PingPlugin.PingTrackers.ComponentModelPingTracker.PingLoop(CancellationToken token) in K:\arashiiro\PingTrackers\ComponentModelPingTracker.cs:line 23
   --- End of inner exception stack trace ---

**Comment by karashiiro** [comment]
Fixed, will release an update in a minute 👍
