### ISSUE TITLE
Ping extremely low on 2.1.0.0

### ISSUE THREAD

**Issue by Xorag** [karashiiro/PingPlugin#44]
Win 10/Steam Client/No VPNs

Ping for me on this version is usually showing just 1/3/5ms whereas normally my server ping is around 75ms

Seeing this in my log file:

```
2022-02-02 15:10:58.372 -05:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PingPlugin.PingTrackers.PingTracker.UpdateSeAddress() in K:\arashiiro\PingTrackers\PingTracker.cs:line 150
   at PingPlugin.PingTrackers.PingTracker.AddressUpdateLoop(CancellationToken token)
   --- End of inner exception stack trace ---
2022-02-02 15:10:58.373 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wMi0wMlQxNToxMDo1OC4zNzM4NTExLTA1OjAwIiwiSW5mbyI6IlN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IEEgVGFzaydzIGV4Y2VwdGlvbihzKSB3ZXJlIG5vdCBvYnNlcnZlZCBlaXRoZXIgYnkgV2FpdGluZyBvbiB0aGUgVGFzayBvciBhY2Nlc3NpbmcgaXRzIEV4Y2VwdGlvbiBwcm9wZXJ0eS4gQXMgYSByZXN1bHQsIHRoZSB1bm9ic2VydmVkIGV4Y2VwdGlvbiB3YXMgcmV0aHJvd24gYnkgdGhlIGZpbmFsaXplciB0aHJlYWQuIChPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LilcclxuIC0tLT4gU3lzdGVtLk51bGxSZWZlcmVuY2VFeGNlcHRpb246IE9iamVjdCByZWZlcmVuY2Ugbm90IHNldCB0byBhbiBpbnN0YW5jZSBvZiBhbiBvYmplY3QuXHJcbiAgIGF0IFBpbmdQbHVnaW4uUGluZ1RyYWNrZXJzLlBpbmdUcmFja2VyLlVwZGF0ZVNlQWRkcmVzcygpIGluIEs6XFxhcmFzaGlpcm9cXFBpbmdUcmFja2Vyc1xcUGluZ1RyYWNrZXIuY3M6bGluZSAxNTBcclxuICAgYXQgUGluZ1BsdWdpbi5QaW5nVHJhY2tlcnMuUGluZ1RyYWNrZXIuQWRkcmVzc1VwZGF0ZUxvb3AoQ2FuY2VsbGF0aW9uVG9rZW4gdG9rZW4pXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLSIsIkNvbnRleHQiOiJVbm9ic2VydmVkIGV4Y2VwdGlvbiBpbiBUYXNrLiJ9
2022-02-02 15:10:58.373 -05:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PingPlugin.PingTrackers.PingTracker.UpdateSeAddress() in K:\arashiiro\PingTrackers\PingTracker.cs:line 150
   at PingPlugin.PingTrackers.PingTracker.AddressUpdateLoop(CancellationToken token)
   --- End of inner exception stack trace ---
2022-02-02 15:10:58.374 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wMi0wMlQxNToxMDo1OC4zNzM5NzcyLTA1OjAwIiwiSW5mbyI6IlN5c3RlbS5BZ2dyZWdhdGVFeGNlcHRpb246IEEgVGFzaydzIGV4Y2VwdGlvbihzKSB3ZXJlIG5vdCBvYnNlcnZlZCBlaXRoZXIgYnkgV2FpdGluZyBvbiB0aGUgVGFzayBvciBhY2Nlc3NpbmcgaXRzIEV4Y2VwdGlvbiBwcm9wZXJ0eS4gQXMgYSByZXN1bHQsIHRoZSB1bm9ic2VydmVkIGV4Y2VwdGlvbiB3YXMgcmV0aHJvd24gYnkgdGhlIGZpbmFsaXplciB0aHJlYWQuIChPYmplY3QgcmVmZXJlbmNlIG5vdCBzZXQgdG8gYW4gaW5zdGFuY2Ugb2YgYW4gb2JqZWN0LilcclxuIC0tLT4gU3lzdGVtLk51bGxSZWZlcmVuY2VFeGNlcHRpb246IE9iamVjdCByZWZlcmVuY2Ugbm90IHNldCB0byBhbiBpbnN0YW5jZSBvZiBhbiBvYmplY3QuXHJcbiAgIGF0IFBpbmdQbHVnaW4uUGluZ1RyYWNrZXJzLlBpbmdUcmFja2VyLlVwZGF0ZVNlQWRkcmVzcygpIGluIEs6XFxhcmFzaGlpcm9cXFBpbmdUcmFja2Vyc1xcUGluZ1RyYWNrZXIuY3M6bGluZSAxNTBcclxuICAgYXQgUGluZ1BsdWdpbi5QaW5nVHJhY2tlcnMuUGluZ1RyYWNrZXIuQWRkcmVzc1VwZGF0ZUxvb3AoQ2FuY2VsbGF0aW9uVG9rZW4gdG9rZW4pXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLSIsIkNvbnRleHQiOiJVbm9ic2VydmVkIGV4Y2VwdGlvbiBpbiBUYXNrLiJ9
2022-02-02 15:10:58.374 -05:00 [ERR] Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PingPlugin.PingTrackers.PingTracker.UpdateSeAddress() in K:\arashiiro\PingTrackers\PingTracker.cs:line 150
   at PingPlugin.PingTrackers.PingTracker.AddressUpdateLoop(CancellationToken token)
   --- End of inner exception stack trace ---
```

**Comment by karashiiro** [comment]
Is it just always showing low values, or did it suddenly start showing low values after logging out or instancing or something?

**Comment by Xorag** [comment]
After the update to the new version I was stuck at 0 so I reloaded my plugins with the /xldev toolbar

**Comment by karashiiro** [comment]
And is the connected IP address 127.0.0.1, or is it something else? I'll definitely look into this when I have a minute, just not sure what the cause is with this stack trace.

**Comment by Xorag** [comment]
![image](https://user-images.githubusercontent.com/42698965/152232394-c7ad4a5f-1c00-41f3-8c59-19b2f5bd3372.png)

**Comment by karashiiro** [comment]
Released v2.1.1, does this fix it?

**Comment by Xorag** [comment]
Just updated but still seeing low single digit ping:
![image](https://user-images.githubusercontent.com/42698965/152272410-c2611ed8-acbb-43d4-8e85-9dc7fa8bf5f8.png)

**Comment by karashiiro** [comment]
v2.1.2.1, this should do it. If one of the trackers is way higher than the other (as should be the case here) it'll use the higher ping instead of the lower one.

**Comment by Xorag** [comment]
Yup looks back to normal in the 75-80 range, thanks!
